export const repsOptions = [
    "status",
    "binding obligations",
    "non conflict with other obligations",
    "[no reduction of capital]",
    "power and authority",
    "validity and admissibility in evidence",
    "governing law and enforcement",
    "insolvency",
    "no deduction of tax",
    "no filing or stamp taxes",
    "no default",
    "no misleading information",
    "financial statements",
    "[accounting reference date;]",
    "no proceedings pending or threatened",
    "no breach of laws",
    "security and financial indebtedness",
    "ranking of [Permitted Account security] /[Transaction Security]",
    "[good title to assets;]",
    "legal and beneficial ownership of the [Permitted Accounts] /[Charged Property]",
    "[shares;]",
    "[intellectual property;]",
    "Group Structure Chart",
    "pari passu ranking",
    "[environmental compliance and no environmental claims;]",
    "taxation compliance and no tax claims",
    "sanctions; anti-bribery and corruption",
    "centre of main interests and establishments",
    "[public procurement]",
    "[no immunity from suit, execution, attachment or other legal process;]",
    "[private and commercial acts;]",
    "no adverse consequences"
  ];
